CREATE TABLE ORDERK(
   ID INT,
   CONSTRAINT CHEK_ID CHECK (ID < 10000),
   CONSTRAINT ORDERK_ID PRIMARY KEY (ID),
   USER_ID INT UNIQUE,
   ROOM_ID INT UNIQUE,
   DATE_FROM DATE,
   DATE_TO DATE,
   MONEY_PAID DOUBLE(20,2)
);