CREATE TABLE HOTEL(
    ID INT,
    CONSTRAINT HOTEL_ID PRIMARY KEY (ID),
    COUNTRY VARCHAR(20) DEFAULT 'N/A',
    CONSTRAINT CHECK_COUNT CHECK (COUNTRY != 'ROMANIA' OR COUNTRY != 'BELGIUM' OR COUNTRY != 'CHINA' OR COUNTRY != 'UKRAINE'),
    CITY VARCHAR(50) NOT NULL,
    STREET VARCHAR(50)
);