USE database_name;

CREATE TABLE CUSTOMERS (
    ID INT,
    CONSTRAINT CUSTOMERS_ID PRIMARY KEY (ID),
    COMPANY_NAME VARCHAR(20) NOT NULL,
    CONTACT_NAME VARCHAR(20),
    CONTACT_TITLE VARCHAR(20),
    ADDRESS VARCHAR(20),
    CITY VARCHAR(20),
    REGION VARCHAR(50),
    POSTAL_CODE VARCHAR(20),
    COUNTRY VARCHAR(20),
    PHONE VARCHAR(20),
    FAX  VARCHAR(20)
);