USE database_name;

CREATE TABLE PRODUCTS (
    ID INT,
    CONSTRAINT PRODUCTS_ID PRIMARY KEY (ID),
    PRODUCT_NAME VARCHAR(50) NOT NULL,
    SUPPLIER_ID INT,
        CONSTRAINT SUPPLIER_FK FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(ID),
    CATEGORY_ID INT,
        CONSTRAINT CATEGORY_FK FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID),
    QUANTITY_PER_UNIT INT,
    UNIT_PRICE DOUBLE(7,2),
    UNITS_IN_STOCK INT,
    UNITS_OR_ORDER INT,
    REORDER_LEVEL INT,
    DISCONTINUED TINYINT(1)
);