USE database_name;

CREATE TABLE ORDER_DETAILS (
   ORDER_ID INT,
        CONSTRAINT ORDER_FK FOREIGN KEY (ORDER_ID) REFERENCES ORDERS_NEW(ID),
   PRODUCT_ID INT  NOT NULL,
        CONSTRAINT PRODUCT_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID),
   UNIT_PRICE  DOUBLE(7,2) NOT NULL,
   QUANTITY INT  NOT NULL,
   DISCOUNT DOUBLE(7,2) NOT NULL
);