USE database_name;

CREATE TABLE ORDERS_NEW (
    ID INT,
    CONSTRAINT ORDERS_NEW_ID PRIMARY KEY (ID),
    CUSTOMER_ID INT,
        CONSTRAINT CUSTOMER_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID),
    EMPLOYEED_ID INT,
        CONSTRAINT EMPLOYEED_FK FOREIGN KEY (EMPLOYEED_ID) REFERENCES EMPLOYEES(ID),
    ORDER_DATE DATE,
    REQUIRED_DATE DATE,
    SHIPPED_DATE DATE,
    SHIP_VIA INT,
    FREIGHT VARCHAR(50),
    SHIP_NAME   INT,
        CONSTRAINT SHIP_FK FOREIGN KEY (SHIP_NAME) REFERENCES SHHIPPERS(ID),
    SHIP_ADDRESS   VARCHAR(20),
    SHIP_CITY   VARCHAR(20),
    SHIP_REGION   VARCHAR(50),
    SHIP_POSTAL_CODE   VARCHAR(20),
    SHIP_COUNTRY   VARCHAR(20)
);