USE database_name;

CREATE TABLE SUPPLIERS (
    ID INT,
    CONSTRAINT SUPPLIERS_ID PRIMARY KEY (ID),
    COMPANY_NAME VARCHAR(50) NOT NULL,
    CONTACT_NAME VARCHAR(50) NOT NULL,
    CONTACT_TITLE VARCHAR(20),
    ADDRESS VARCHAR(50),
    CITY VARCHAR(20),
    REGION VARCHAR(50),
    POSTAL_CODE VARCHAR(20),
    COUNTRY VARCHAR(20),
    PHONE   VARCHAR(20),
    FAX     VARCHAR(20),
    HOME_PAGE   VARCHAR(50)
);