CREATE TABLE MOVIE_STAT(
   MOVIE_ID INT,
   CONSTRAINT STAT_ID PRIMARY KEY (MOVIE_ID),
   RATING DOUBLE(3,1),
   CONSTRAINT CHEK_RATING CHECK (RATING >= 1 AND RATING <= 10 ),
   DOMESTIC_SALES INT,
   INTERNATIONAL_SALES INT
);