CREATE TABLE MOVIE(
   ID INT,
   CONSTRAINT MOVIE_ID PRIMARY KEY (ID),
   TITLE VARCHAR(50) UNIQUE NOT NULL ,
   DIRECTOR VARCHAR(20) NOT NULL ,
   DATE_YEAR YEAR(4),
   LENGTH_MINS INT,
   CONSTRAINT CHEK_MOVIE CHECK (LENGTH_MINS > 10 AND LENGTH_MINS < 200 )
);
