-- выборка всех фильмов от самых новых до самых старых по убыванию
SELECT * FROM MOVIE
ORDER BY DATE_YEAR DESC;

-- выборка с таблицы MOVIE_STAT c наибольшими INTERNATIONAL_SALES по убыванию
SELECT MOVIE.DIRECTOR, MOVIE.TITLE,MOVIE_STAT.INTERNATIONAL_SALES FROM MOVIE,MOVIE_STAT
WHERE MOVIE_STAT.MOVIE_ID = MOVIE.ID
ORDER BY INTERNATIONAL_SALES  DESC;