USE database_name;
--изменяет РК таблицы SupplierID на Phone
        -- удяляем из PRODUCTS FOREIGN KEY == SUPPLIER_FK
        -- удяляем из SUPPLIERS текущий PRIMARY KEY
        -- создаем новый PRIMARY KEY = PHONE
        -- в PRODUCTS SUPPLIER_ID меняем с INT на VARCHAR
        -- в PRODUCTS устанавливаем новый FOREIGN KEY = SUPPLIERS.PHONE

ALTER TABLE PRODUCTS
DROP FOREIGN KEY SUPPLIER_FK;

ALTER TABLE SUPPLIERS
DROP PRIMARY KEY,
ADD CONSTRAINT SUPPLIERS_ID PRIMARY KEY (PHONE);

ALTER TABLE PRODUCTS
MODIFY SUPPLIER_ID VARCHAR(20),
ADD CONSTRAINT SUPPLIER_FK FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS (PHONE);