--имена клиентов, их город, имена менеджеров по продажам и их город, где сумма сделки была больше 10000*
SELECT CUSTOMER.CUSTNAME, CUSTOMER.CITY, SALESMAN.NAME, SALESMAN.CITY
FROM SALESMAN
JOIN CUSTOMER ON SALESMAN.SALESMAN_ID = CUSTOMER.SALESMAN_ID
JOIN DEALS ON CUSTOMER.CUSTOMER_ID = DEALS.CUSTOMER_ID AND AMOUNT <10000;


--имена клиентов, которые делали сделки в 2017 - 2018 году*
SELECT CUSTOMER.CUSTNAME
FROM CUSTOMER
JOIN DEALS ON CUSTOMER.CUSTOMER_ID = DEALS.CUSTOMER_ID  AND  DATE_DEAL BETWEEN ('2017-01-01') AND ('2017-12-31');


--имя лучшего менеджера по продажам по сумме сделок за август 2017 год*
SELECT new_name, MAX(max_sum)
FROM SALESMAN,(
SELECT SALESMAN.NAME AS new_name, SUM(DEALS.AMOUNT) AS max_sum
FROM SALESMAN
JOIN CUSTOMER ON SALESMAN.SALESMAN_ID = CUSTOMER.SALESMAN_ID
JOIN DEALS ON CUSTOMER.CUSTOMER_ID = DEALS.CUSTOMER_ID  AND  DATE_DEAL BETWEEN ('2017-08-01') AND ('2017-08-31')
GROUP BY new_name) a;